const navToggle = require('./modules/navToggle.js');
const flipperRotate = require('./modules/flipperRotate.js');
const scroll = require('./modules/scroll.js');
const sticky = require('./modules/sticky.js');
const highlight = require('./modules/highlightNav.js');
const parallax = require('./modules/parallax.js');
const blur = require('./modules/blur.js');
const preloader = require('./modules/preloader.js');
const formActions = require('./modules/formActions.js');
const slider = require('./modules/slider.js');

navToggle();
flipperRotate();
scroll();
sticky();
highlight();
parallax();
blur();
preloader();
formActions();
slider();